#
# Copyright (C) Stealth Software Technologies, Inc.
#
# For the complete copyright information, please see the
# associated README file.
#
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages: [stage_1]

build:
  stage: stage_1
  image: registry.stealthsoftwareinc.com/stealth/builder-images/ubuntu:20.04
  script:
    - apt-get -q -y install python3-pip sudo
    - pip install .
    - wget https://raw.githubusercontent.com/emp-toolkit/emp-readme/master/scripts/install.py
    - python3 install.py --deps --tool --ot --zk
    - export LD_LIBRARY_PATH=/usr/local/lib
    - ./bash/neural_networks.sh
    - ./bash/crypto.sh
    - ./bash/simple.sh
    - ./bash/misc.sh
