from setuptools import setup

setup(name='miniwizpl',
      version='0.1',
      description='miniWizPL library & compiler for writing zero-knowledge statements',
      url='none',
      author='Joe Near',
      author_email='jnear@uvm.edu',
      license='GPLv3',
      packages=['miniwizpl'],
      install_requires=[
          'certifi==2022.5.18.1',
          'cffi==1.15.0',
          'charset-normalizer==2.0.12',
          'cryptography==37.0.1',
          'idna==3.3',
          'numpy==1.22.4',
          'Pillow==9.1.1',
          'pycparser==2.21',
          'requests==2.28.0',
          'torch==1.6.0',
          'torchvision==0.7.0',
          'typing_extensions==4.2.0',
          'urllib3==1.26.9'],
      package_data={'': ['boilerplate/*']},
      include_package_data=True,
      zip_safe=False)
